const data = [
    {
        id: 1,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does she do?",
        backInFinnish: "JUOKSEE", 
        backInEnglish: "runs", 
        imgSrc: 'https://tse1.mm.bing.net/th?id=OIP.gAygpSej0Q2Sq0yNaoIPXgHaG0&pid=Api&P=0',
    }, 
    {
        id: 2,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does he do?",
        backInFinnish: "LAULAA",
        backInEnglish: "sings",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.h8LR_LOKHJfppsBrZjzHygHaEK&pid=Api&P=0',
    },
    {
        id: 3,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "HYPPÄÄVÄT",
        backInEnglish: "jump",
        imgSrc: 'https://tse1.mm.bing.net/th?id=OIP.RbkQyk2lGtj3kuiecBHW0QHaE7&pid=Api&P=0',
    },
    {
        id: 4,
        frontInFinnish: "MITÄ VAUVA TEKEE?",
        frontInEnglish: "What does the baby do?",
        backInFinnish: "NUKKUU",
        backInEnglish: "sleeps",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.kbqmjmB9UW5aaBoAFyDv9QHaF3&pid=Api&P=0',
    },
    {
        id: 5,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does she do?",
        backInFinnish: "ITKEE",
        backInEnglish: "cries",
        imgSrc: 'https://tse3.mm.bing.net/th?id=OIP.Xr-8xhRBUqQAi9XGdT4BngHaFj&pid=Api&P=0',
    },
    {
        id: 6,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What does they do?",
        backInFinnish: "HENGITTÄVÄT",
        backInEnglish: "breathe",
        imgSrc:'https://tse1.mm.bing.net/th?id=OIP.Vy9l4kLdCoFBIctf-HEwGgHaE8&pid=Api&P=0',
    },
    {
        id: 7,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "TANSSIVAT",
        backInEnglish: "dance",
        imgSrc: 'https://tse2.explicit.bing.net/th?id=OIP.svymOnPPa32QU2luiiUVKgHaC1&pid=Api&P=0',
    },
    {
        id: 8,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does he do?",
        backInFinnish: "AJAA",
        backInEnglish: "drives",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.TKyADN-boZODNEygt6D9zwHaD5&pid=Api&P=0',
    },
    {
        id: 9,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does she do?",
        backInFinnish: "NAURAA",
        backInEnglish: "smiles",
        imgSrc: 'https://tse1.mm.bing.net/th?id=OIP.HS29UWpaS5hH6ty8DwknCgHaFM&pid=Api&P=0=0',
    },
    {
        id: 10,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does she do?",
        backInFinnish: "LEPÄÄ",
        backInEnglish: "rests",
        imgSrc: 'https://tse2.mm.bing.net/th?id=OIP.ybauw4sz3gNGw6I9F-DlJgHaFc&pid=Api&P=0',
    },
    {
        id: 11,
        frontInFinnish: "MITÄ HÄN TEKEE?",
        frontInEnglish: "What does she do?",
        backInFinnish: "LUKEE",
        backInEnglish: "reads",
        imgSrc: 'https://tse3.explicit.bing.net/th?id=OIP.yqmtqOaG71-dn5nfPNzPjQHaDq&pid=Api&P=0',
    },
    {
        id: 12,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },
    {
        id: 13,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },
    {
        id: 14,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },
    {
        id: 15,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },
    {
        id: 16,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 17,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 18,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 19,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 20,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 21,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 22,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 23,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },{
        id: 24,
        frontInFinnish: "MITÄ HE TEKEVÄT?",
        frontInEnglish: "What do they do?",
        backInFinnish: "KATSELEVAT",
        backInEnglish: "watch",
        imgSrc: 'https://tse4.mm.bing.net/th?id=OIP.a9JeMJaO7obLNlCOo2Va9QHaEK&pid=Api&P=0',
    },
]

export default data;